[PHP]
date.timezone=UTC

[xdebug]
xdebug.mode=debug
xdebug.start_with_request=trigger
; the host (your IDE) as seen from inside the container = subnet gateway
xdebug.client_host=192.168.64.1
xdebug.client_port=9003
